### ISSUE TITLE
I'm getting this error when I'm trying to make an .exe file through pyinstaller - "ModuleNotFoundError: No module named 'acrcloud_extr_tool'" on Python 3.7, Win10-64bit

### ISSUE THREAD

**Issue by waitwhatisthis97** [acrcloud/acrcloud_sdk_python#11]

**Comment by waitwhatisthis97** [comment]
I solved it. Turns out due to it being a binary file, it had to be added explicitly in the .spec file (read the pyinstaller documentation). I did it and it ran like a charm.

**Comment by oliverwood93** [comment]
How did you end up fixing this issue, I have the same thing on Linux and I'm at a loss

**Comment by fortyTwo102** [comment]
Hey oliverwood93 (hp reference?) the pyinstaller simply couldn't find the .pyd file on its own, so I just added the directory of the file explicitly in .spec file and it worked.

**Comment by jayfeldmann** [comment]
Hey there, im new to pyinstall and have stumbled upon the same error i also read an answer on stack overflow, which did not help. Can anybody please clarify what exaclty has to be done? I checked the pyinstaller documentation but i just dont know what to do with it? If you have the answer, please enlighten me.

**Comment by fortyTwo102** [comment]
Hi, this is all you need. 
https://youtu.be/OZSZHmWSOeM

**Comment by jayfeldmann** [comment]
thx for the reply, but the video doesnt really help me. As i told, I'm new to the "python-to-exe" game since I usually create c# programs. My problem right now is, I dont understand what input pyinstaller/the program from your video expects from me? I tried adding the folder with the acrcloud_extr_tool.pyd via "Additional files", i tried to add the file directly via "Additional Files", i tried adding the .pyd via "--add-binary" but nothing seems to work. Either i misunderstand the use of those parameters or im entering the wrong syntax. Because, now i am at this point: Either i enter a folder in one of those fields and the module missing error remains or i get an "win 5; access denied" error during building.

**Comment by jayfeldmann** [comment]
Ok, now i Finally managed it, i added the line: a.binaries.append(('acrcloud_extr_tool','<FILEPATH>\\acrcloud_extr_tool.pyd','BINARY'))
to the .specs file and it did the job.
